name: localization_json_loader
description: A new Flutter localization_json_loader package.
version: 2.0.0
homepage: https://github.com/flutter-fast-kit/localization_json_loader

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path_provider: ^2.0.1
  sp_util: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter